### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by ElvarP** [Dadzemovic/LeagueSort#1]
Hey this is exactly what i was looking for (Well not exactly, i was going to just put data from about 100 summoners into a database) But this solution doesn't seem to be working. I think LOL i'm kind of a noob.

**Comment by Dadzemovic** [comment]
Are you supplying your own database credentials? You must have a table in your database called 'wldata', with columns 'wins', 'losses', and 'id'.

Also, since you are only concerned about collecting the summoner data (cronjob.php), take note that the current implementation (as of 5/17/2015) is infinitely recursive.

What is your final goal? Perhaps I can tweak the code to better suit your needs.

**Comment by ElvarP** [comment]
Yeah i was supplying my own database credentials but when i run cronjob.php it gives me this error "Fatal error: Maximum function nesting level of '100' reached, aborting! in C:\wamp\www\riotapi\LeagueSort-master\cronjob.php on line 14

Yeah i realized it was infinetly recursive, but isn't it supposed to be? I thought this was supposed to get summoner data from every summoner.

At the moment my final goal is is:
1. User inputs summonername into a form and selects his server
2. The Riot api gets his summoner id and saves the id into the database
3. Cronjob runs a API request for every summoner ID in the database and saves their league, 
   league points, ranked wins, ranked losses and their top 5 most played champs champions
4. Then list every summoner in a table with their stats (like this: http://i.imgur.com/QfJNUu7.png).

But yeah i only need help with collecting the summoner data.

**Comment by Dadzemovic** [comment]
Hey, I've converted the code to utilize an infinite loop rather than infinite recursion, and made a few other small optimizations. Let me know if it fixes your problem.

Note, however, that this code attempts to store league data from ALL summoners, not just a specific subset in your database. The code must be adjusted accordingly. Let me know if you need any pointers.

**Comment by ElvarP** [comment]
Yep, that fixed the problem. Thanks for this, it helped a lot!

**Comment by ElvarP** [comment]
Ok, since you said i can ask you for pointers i hope you can help me :P

What i'm trying to do is make Cronjob.php save the summoners league, 
league points, ranked wins, ranked losses and (maybe) their top 5 most played champs champions.

So i have a table with Summoner ID's, but i don't know how to make Cronjob.php loop through the Summoner ID's in the table, instead of every summoner

Can you give me some tips/pointers? :+1: I'd appreciate it but i understand if you can't.

**Comment by Dadzemovic** [comment]
So your steps would be:
- Loop through each column in your database
  - For each summoner ID, hit Riot's API and retrieve the data you mentioned (LP, wins, losses)
  - Add this data to the database for the current summoner

However, my intuition tells me that it would probably be better to just grab this data as soon as the user submits their summoner name, rather than in the two steps you want to employ (add ID to database, then the remaining stats).

**Comment by ElvarP** [comment]
Yeah i'd agree, but i'm not sure how the database would update? I'd like for the database update every 24 hours or so.

**Comment by Dadzemovic** [comment]
OK. Since you are only collecting data for summoners who input their name, are you sure you need to be storing the data at all? Could you just feed them the data directly from the api, whenever it is requested?

**Comment by ElvarP** [comment]
Yeah but i'm going to be listing a table with every summoner, so figured making a direct api request for 500 ish summoners would take a lot of time and be quite inneficient.

**Comment by Dadzemovic** [comment]
OK, makes sense. Basically you want a cronjob that runs every 24 hrs that doesn't infinitely loop, but rather loops through your database and does what I bullet pointed in a comment above. Let me know if you have any specific questions with regards to this task.

**Comment by ElvarP** [comment]
Fuck man, i thought this was going to be really easy. I tried googling but i had no idea what to search for.

Could you help me with this? I'd be glad to pay if you have paypal.

**Comment by Dadzemovic** [comment]
Yeah, I'd be glad to take a look. You can shoot me details at deen_adzemovic@hotmail.com

**Comment by ElvarP** [comment]
Sent you a mail :)
